DELETE FROM categoriesgames;
DELETE FROM rounds;
DELETE FROM games;

DELETE FROM users;
DELETE FROM answers;
DELETE FROM questions;
DELETE FROM categories;

ALTER TABLE categoriesgames AUTO_INCREMENT = 1;
ALTER TABLE rounds AUTO_INCREMENT = 1;
ALTER TABLE games AUTO_INCREMENT = 1;
ALTER TABLE users AUTO_INCREMENT = 1;
ALTER TABLE answers AUTO_INCREMENT = 1;
ALTER TABLE questions AUTO_INCREMENT = 1;
ALTER TABLE categories AUTO_INCREMENT = 1;