CREATE DATABASE WerWirdMillionaer;

USE WerWirdMillionaer;

CREATE TABLE Kategorien (
	KategorieID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	Name VARCHAR(100) NOT NULL,
	PRIMARY KEY (KategorieID)
);

CREATE TABLE Fragen (
	FrageID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	KategorieID INT UNSIGNED NOT NULL,
	Frage TEXT NOT NULL,
	PRIMARY KEY (FrageID),
	CONSTRAINT FK_KategorieFrage FOREIGN KEY (KategorieID) REFERENCES Kategorien(KategorieID)
);

CREATE TABLE Antworten (
	AntwortID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	FrageID INT UNSIGNED NOT NULL,
	Antwort TEXT NOT NULL,
	Richtig BOOLEAN NOT NULL,
	PRIMARY KEY (AntwortID),
	CONSTRAINT FK_FrageAntwort FOREIGN KEY (FrageID) REFERENCES Fragen(FrageID)
);

CREATE TABLE Users (
	UserID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	Username VARCHAR(100) NOT NULL,
	IsAdmin BOOLEAN NOT NULL,
	Salt VARCHAR(32) NOT NULL,
	Password VARCHAR(64) NOT NULL,
	PRIMARY KEY (UserID)
);

CREATE TABLE Spiele (
	SpielID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	UserID INT UNSIGNED NOT NULL,
	Start DATETIME NOT NULL,
	PRIMARY KEY (SpielID),
	CONSTRAINT FK_UserSpiel FOREIGN KEY (UserID) REFERENCES Users(UserID)
);

CREATE TABLE Spielrunden (
	SpielrundeID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	SpielID INT UNSIGNED NOT NULL,
	FrageID INT UNSIGNED NOT NULL,
	AntwortID INT UNSIGNED,
	Dauer INT UNSIGNED NOT NULL,
	JokerVerwendet BOOLEAN NOT NULL,
	PRIMARY KEY (SpielrundeID),
	CONSTRAINT FK_SpielSpielrunde FOREIGN KEY (SpielID) REFERENCES Spiele(SpielID),
	CONSTRAINT FK_FrageSpielrunde FOREIGN KEY (FrageID) REFERENCES Fragen(FrageID),
	CONSTRAINT FK_AntwortSpielrunde FOREIGN KEY (AntwortID) REFERENCES Antworten(AntwortID)
);

CREATE TABLE KategorienSpiele (
	KategorienSpieleID INT UNSIGNED AUTO_INCREMENT NOT NULL,
	KategorieID INT UNSIGNED NOT NULL,
	SpielID INT UNSIGNED NOT NULL,
	PRIMARY KEY (KategorienSpieleID),
	CONSTRAINT FK_KategorieKategorienSpiele FOREIGN KEY (KategorieID) REFERENCES Kategorien(KategorieID),
	CONSTRAINT FK_SpielKategorienSpiele FOREIGN KEY (SpielID) REFERENCES Spiele(SpielID)
);