CREATE TABLE Spiele (
	SpielID UNSIGNED INT AUTO_INCREMENT NOT NULL,
	UserID UNSIGNED INT NOT NULL,
	Start DATETIME NOT NULL,
	Ende DATETIME NOT NULL,
	Punktzahl INT NOT NULL,
	PRIMARY KEY (SpielID),
	FOREIGN KEY (UserID) REFERENCES Users(USERID)
);