CREATE TABLE Fragen (
	FrageID UNSIGNED INT AUTO_INCREMENT NOT NULL,
	KategorieID UNSIGNED INT NOT NULL,
	Frage TEXT NOT NULL,
	PRIMARY KEY (FrageID),
	FOREIGN KEY (KategorieID) REFERENCES Kategorien(KategorieID)
);