CREATE TABLE Users (
	UserID UNSIGNED INT AUTO_INCREMENT NOT NULL,
	Username VARCHAR(100) NOT NULL,
	IsAdmin BOOLEAN NOT NULL,
	Salt VARCHAR(32) NOT NULL,
	Password VARCHAR(64) NOT NULL,
	PRIMARY KEY (UserID)
);